# .travis.yml
env:
  global:
    - CI_NAME=travis-ci

matrix:
  include:
    - language: node_js
      sudo: required
      node_js:
        - "5"
      before_install:
        - npm install mocha -g
        - npm install 
      script:
        - cd myapp
        - npm start
