# .travis.yml
env:
  global:
    - CI_NAME=travis-ci

matrix:
  include:
    - language: node_js
      sudo: required
      node_js:
        - "5"
      #before_script:
      #  - npm install mosca --save
      script:
        - node app.js
